"""LLM-driven proposal generator using kernel WorkerPool for admission control.

Each proposal is generated by an LLM worker with a distinct perspective.
Workers are gated by WorkerPoolManager slot claims (WorkerRole.planner) and
each call is tracked as a Step + StepAttempt for full governance audit.
"""

from __future__ import annotations

import concurrent.futures
import json
import time
import uuid
from collections.abc import Callable
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, cast

import structlog

from hermit.kernel.execution.competition.deliberation import CandidateProposal
from hermit.kernel.execution.workers.models import WorkerRole

if TYPE_CHECKING:
    from hermit.kernel.artifacts.models.artifacts import ArtifactStore
    from hermit.kernel.execution.workers.pool import WorkerPoolManager
    from hermit.kernel.ledger.journal.store import KernelStore
    from hermit.runtime.provider_host.shared.contracts import Provider

__all__ = ["ProposalGenerator", "ProposalPerspective"]

log = structlog.get_logger()

_FUTURES_TIMEOUT_SECONDS = 120
_DEFAULT_MAX_TOKENS = 4096


@dataclass(frozen=True)
class ProposalPerspective:
    """A viewpoint from which an LLM worker generates a proposal."""

    role: str
    system_prompt: str
    model: str | None = None


_DEFAULT_PERSPECTIVES: tuple[ProposalPerspective, ...] = (
    ProposalPerspective(
        role="conservative",
        system_prompt=(
            "You are a conservative software engineer.  Prioritise safety, "
            "minimal blast radius, and incremental changes.  Prefer well-tested "
            "approaches over novel solutions.  Always include rollback steps."
        ),
    ),
    ProposalPerspective(
        role="aggressive",
        system_prompt=(
            "You are an ambitious software architect.  Prioritise velocity and "
            "structural improvement.  Propose bold refactors when the payoff is "
            "clear.  Accept higher short-term risk for long-term reward."
        ),
    ),
    ProposalPerspective(
        role="balanced",
        system_prompt=(
            "You are a pragmatic tech lead.  Balance risk against reward.  "
            "Consider cost, timeline, and team capacity.  Propose the plan that "
            "maximises delivered value per unit of effort."
        ),
    ),
)


def _parse_json_response(raw_text: str) -> dict[str, Any]:
    """Extract the first JSON object from an LLM response."""
    text = raw_text.strip()
    if text.startswith("```"):
        first_nl = text.index("\n") if "\n" in text else len(text)
        text = text[first_nl + 1 :]
    if text.endswith("```"):
        text = text[: text.rfind("```")]
    text = text.strip()

    try:
        parsed: Any = json.loads(text)
        if isinstance(parsed, dict):
            return cast(dict[str, Any], parsed)
    except json.JSONDecodeError:
        pass

    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end > start:
        try:
            fallback: Any = json.loads(text[start : end + 1])
            if isinstance(fallback, dict):
                return cast(dict[str, Any], fallback)
        except json.JSONDecodeError:
            pass
    return {}


class ProposalGenerator:
    """Generates competing proposals using pool-gated parallel LLM calls.

    Each LLM call claims a ``WorkerRole.planner`` slot from the pool and
    creates a kernel Step + StepAttempt for governance audit.
    """

    def __init__(
        self,
        provider_factory: Callable[[], Provider],
        *,
        default_model: str,
        max_workers: int = 3,
        perspectives: tuple[ProposalPerspective, ...] | None = None,
    ) -> None:
        self._provider_factory = provider_factory
        self._default_model = default_model
        self._max_workers = max_workers
        self._perspectives = perspectives or _DEFAULT_PERSPECTIVES

    def generate_proposals(
        self,
        debate_id: str,
        decision_point: str,
        context: dict[str, Any],
        *,
        task_id: str,
        pool: WorkerPoolManager,
        store: KernelStore,
        artifact_store: ArtifactStore,
    ) -> list[CandidateProposal]:
        """Generate proposals in parallel — one per perspective, pool-gated.

        Each worker claims a ``WorkerRole.planner`` slot before calling the LLM.
        Slots are released after the call completes (or fails).
        """
        log.info(
            "llm_proposer.generating",
            debate_id=debate_id,
            perspective_count=len(self._perspectives),
        )

        proposals: list[CandidateProposal] = []

        with concurrent.futures.ThreadPoolExecutor(
            max_workers=self._max_workers,
        ) as executor:
            futures: dict[concurrent.futures.Future[CandidateProposal | None], str] = {}
            for perspective in self._perspectives:
                future = executor.submit(
                    self._generate_single_pooled,
                    perspective,
                    debate_id,
                    decision_point,
                    context,
                    task_id=task_id,
                    pool=pool,
                    store=store,
                    artifact_store=artifact_store,
                )
                futures[future] = perspective.role

            done, not_done = concurrent.futures.wait(
                futures.keys(),
                timeout=_FUTURES_TIMEOUT_SECONDS,
            )

            for future in done:
                role = futures[future]
                try:
                    result = future.result()
                    if result is not None:
                        proposals.append(result)
                        log.debug(
                            "llm_proposer.proposal_generated",
                            debate_id=debate_id,
                            role=role,
                            candidate_id=result.candidate_id,
                        )
                except Exception:
                    log.warning(
                        "llm_proposer.worker_failed",
                        debate_id=debate_id,
                        role=role,
                        exc_info=True,
                    )

            for future in not_done:
                role = futures[future]
                future.cancel()
                log.warning("llm_proposer.worker_timeout", debate_id=debate_id, role=role)

        log.info(
            "llm_proposer.completed",
            debate_id=debate_id,
            proposal_count=len(proposals),
        )
        return proposals

    def _generate_single_pooled(
        self,
        perspective: ProposalPerspective,
        debate_id: str,
        decision_point: str,
        context: dict[str, Any],
        *,
        task_id: str,
        pool: WorkerPoolManager,
        store: KernelStore,
        artifact_store: ArtifactStore,
    ) -> CandidateProposal | None:
        """Claim a planner slot, create a step, run LLM, release slot."""
        slot = pool.claim_slot(
            WorkerRole.planner,
            supervisor_id=task_id,
            workspace=debate_id,
            module="deliberation_proposal",
        )
        if slot is None:
            log.warning(
                "llm_proposer.slot_unavailable",
                debate_id=debate_id,
                role=perspective.role,
            )
            return None

        # Create a kernel step for audit trail.
        step = store.create_step(
            task_id=task_id,
            kind="plan",
            title=f"deliberation_proposal:{perspective.role}",
        )
        attempt = store.create_step_attempt(
            task_id=task_id,
            step_id=step.step_id,
            executor_mode="deliberation_proposer",
        )

        try:
            result = self._generate_single(
                perspective, debate_id, decision_point, context
            )

            # Store LLM output as artifact linked to step.
            if result is not None:
                artifact_payload = {
                    "artifact_type": "deliberation_llm_proposal",
                    "debate_id": debate_id,
                    "step_id": step.step_id,
                    "attempt_id": attempt.step_attempt_id,
                    "slot_id": slot.slot_id,
                    "perspective": perspective.role,
                    "plan_summary": result.plan_summary,
                    "expected_cost": result.expected_cost,
                    "expected_risk": result.expected_risk,
                    "expected_reward": result.expected_reward,
                }
                artifact_store.store_json(artifact_payload)

            store.update_step_attempt(attempt.step_attempt_id, status="succeeded")
            store.update_step(step.step_id, status="completed")
            return result
        except Exception:
            store.update_step_attempt(attempt.step_attempt_id, status="failed")
            store.update_step(step.step_id, status="failed")
            raise
        finally:
            pool.release_slot(slot.slot_id)

    def _generate_single(
        self,
        perspective: ProposalPerspective,
        debate_id: str,
        decision_point: str,
        context: dict[str, Any],
    ) -> CandidateProposal | None:
        """Run a single LLM call to produce one proposal."""
        from hermit.runtime.provider_host.shared.contracts import ProviderRequest

        provider = self._provider_factory()
        model = perspective.model or self._default_model

        context_json = json.dumps(context, indent=2, default=str)
        user_prompt = (
            f"## Decision Point\n{decision_point}\n\n"
            f"## Context\n```json\n{context_json}\n```\n\n"
            "Generate a proposal as a JSON object with these fields:\n"
            '- "plan_summary": concise description of the approach\n'
            '- "contract_draft": dict of concrete steps/scope\n'
            '- "expected_cost": "low" | "medium" | "high"\n'
            '- "expected_risk": "low" | "medium" | "high"\n'
            '- "expected_reward": "low" | "medium" | "high"\n\n'
            "Return ONLY a JSON object, no other text."
        )

        request = ProviderRequest(
            model=model,
            max_tokens=_DEFAULT_MAX_TOKENS,
            system_prompt=perspective.system_prompt,
            messages=[{"role": "user", "content": user_prompt}],
        )

        response = provider.generate(request)

        raw_text = ""
        for block in response.content:
            if hasattr(block, "get") and block.get("type") == "text":
                raw_text += block.get("text", "")

        parsed = _parse_json_response(raw_text)
        if not parsed:
            log.warning(
                "llm_proposer.parse_failed",
                debate_id=debate_id,
                role=perspective.role,
                raw_length=len(raw_text),
            )
            return None

        candidate_id = f"llm_prop_{uuid.uuid4().hex[:12]}"
        return CandidateProposal(
            candidate_id=candidate_id,
            proposer_role=perspective.role,
            target_scope=debate_id,
            plan_summary=str(parsed.get("plan_summary", "")),
            contract_draft=dict(parsed.get("contract_draft", {})),
            expected_cost=str(parsed.get("expected_cost", "medium")),
            expected_risk=str(parsed.get("expected_risk", "medium")),
            expected_reward=str(parsed.get("expected_reward", "medium")),
            created_at=time.time(),
        )
